//Get all continents types
export const GET_CONTINENTS_REQUEST = 'GET_CONTINENTS_REQUEST';
export const GET_CONTINENTS_SUCCESS = 'GET_CONTINENTS_SUCCESS';
export const GET_CONTINENTS_FAIL = 'GET_CONTINENTS_FAIL'